# Generated by Django 5.2.7 on 2025-11-01 14:18

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username already exists.'}, help_text='Required. 30 characters or fewer. Lowercase letters, numbers and underline.', max_length=30, unique=True, validators=[utils.validators.UsernameValidator()]),
        ),
    ]
